import { competitions, createDefaultGameConfig } from './competitions'
import type { Competition, Round, Stage, Session, Split } from './competitions'
import { registrations } from './registrations'
import type { Registration } from './registrations'
import { protests } from './protests'
import type { Protest } from './protests'
import { serverInstances } from './servers'
import { drivers } from './drivers'
import { bump } from './store'

export const DEMO_COMP_ID = 'demo_comp'
export const DEMO_ROUND_ID = 'demo_comp_r1'
export const DEMO_RACE_STAGE_ID = 'demo_comp_r1_race'
export const DEMO_FINAL_STAGE_ID = 'demo_comp_r1_final'
export const DEMO_RACE_SPLIT_ID = 'demo_comp_r1_race_sp1'
export const DEMO_RACE_SESSION_ID = 'demo_comp_r1_race_se_r'

const DEMO_DRIVER_COUNT = 8
const DEMO_NUMBERS = [7, 23, 14, 88, 11, 5, 44, 3]

function buildSessions(stageId: string): Session[] {
  return [
    { id: `${stageId}_se_p`, type: 'practice', name_zh: '练习赛', name_en: 'Practice', durationMinutes: 20 },
    { id: `${stageId}_se_q`, type: 'qualifying', name_zh: '排位赛', name_en: 'Qualifying', durationMinutes: 15 },
    { id: `${stageId}_se_r`, type: 'race', name_zh: '正赛', name_en: 'Race', raceDuration: 30, raceDurationType: 'time' },
  ]
}

function buildSplit(stageId: string, splitNumber: number, serverName: string): Split {
  return {
    id: `${stageId}_sp${splitNumber}`,
    splitNumber,
    serverName,
    serverPassword: 'demo2026',
    adminPassword: 'admin',
    spectatorPassword: '',
    maxConnections: 30,
    registerToLobby: true,
    udpPort: 9600,
    tcpPort: 9600,
    httpPort: 8081,
    maxCarSlots: 30,
    isRaceLocked: 1,
    dumpLeaderboards: 1,
    dumpEntryList: 1,
  }
}

function buildDemoCompetition(): Competition {
  const now = Date.now()
  const at = (hoursFromNow: number) => new Date(now + hoursFromNow * 3_600_000).toISOString()
  const gameConfig = { ...createDefaultGameConfig('ACC'), track: 'monza', carGroup: 'GT3' }

  const raceStage: Stage = {
    id: DEMO_RACE_STAGE_ID,
    roundId: DEMO_ROUND_ID,
    type: 'race_day',
    name_zh: '正赛日',
    name_en: 'Race Day',
    description_zh: '练习、排位、正赛一气呵成，单服务器组别。',
    description_en: 'Practice, qualifying and race in a single day on one server.',
    startsAt: at(-26),
    endsAt: at(-2),
    gameConfig,
    sessions: buildSessions(DEMO_RACE_STAGE_ID),
    splits: [buildSplit(DEMO_RACE_STAGE_ID, 1, 'Demo GT3 Monza #1')],
    eligibilitySource: 'roundRegistration',
    maxEntriesPerSplit: 30,
    enableMultiSplit: false,
    minEntries: 4,
  }

  const finalStage: Stage = {
    id: DEMO_FINAL_STAGE_ID,
    roundId: DEMO_ROUND_ID,
    type: 'final',
    name_zh: '决赛',
    name_en: 'Final',
    description_zh: '正赛日前 6 名晋级，争夺本站冠军。',
    description_en: 'Top 6 from the race day advance to fight for the win.',
    startsAt: at(46),
    endsAt: at(49),
    gameConfig,
    sessions: buildSessions(DEMO_FINAL_STAGE_ID),
    splits: [buildSplit(DEMO_FINAL_STAGE_ID, 1, 'Demo GT3 Monza Final')],
    eligibilitySource: 'previousStageResult',
    advancementRule: { metric: 'position', limit: 6, targetStageId: DEMO_FINAL_STAGE_ID, fallbackPolicy: 'fillNext' },
    maxEntriesPerSplit: 30,
    enableMultiSplit: false,
    minEntries: 4,
  }

  const round: Round = {
    id: DEMO_ROUND_ID,
    competitionId: DEMO_COMP_ID,
    roundNumber: 1,
    name_zh: '第 1 站 - 蒙扎',
    name_en: 'Round 1 - Monza',
    track: 'Monza',
    trackLayout: 'GP',
    registrationOpenAt: at(-24 * 14),
    registrationCloseAt: at(-48),
    cancelRegistrationDeadline: at(-72),
    stages: [raceStage, finalStage],
    currentRegistrations: 0,
    registeredDriverIds: [],
  }

  return {
    id: DEMO_COMP_ID,
    isDemo: true,
    name_zh: '【演示】流程示例赛事',
    name_en: '[Demo] Flow Example Competition',
    description_zh: '由赛事流程助手生成，用于演示从报名、开服、回收成绩到发布晋级的完整闭环。可随时一键重置。',
    description_en: 'Generated by the flow assistant to demonstrate the full loop: registration, server, results, publishing and advancement. Reset anytime.',
    coverImage: '',
    regions: ['CN'],
    game: 'ACC',
    carClass: 'GT3',
    defaultRuleset: {
      scoringTable: [
        { position: 1, points: 25 },
        { position: 2, points: 18 },
        { position: 3, points: 15 },
        { position: 4, points: 12 },
        { position: 5, points: 10 },
        { position: 6, points: 8 },
        { position: 7, points: 6 },
        { position: 8, points: 4 },
      ],
      scoringNote_zh: '演示用标准积分表，前 8 名得分。',
      scoringNote_en: 'Demo standard scoring table, points to top 8.',
    },
    rounds: [round],
    createdBy: 'admin1',
    createdAt: new Date(now).toISOString(),
    updatedAt: new Date(now).toISOString(),
  }
}

function buildDemoRegistrations(): Registration[] {
  const now = Date.now()
  return drivers.slice(0, DEMO_DRIVER_COUNT).map((d, i) => ({
    id: `demo_reg_${i + 1}`,
    competitionId: DEMO_COMP_ID,
    roundId: DEMO_ROUND_ID,
    driverId: d.id,
    platformId: '7656119' + String(8200000000 + i),
    preferredNumber: DEMO_NUMBERS[i] ?? 10 + i,
    teamId: d.teamId,
    status: 'pending',
    paymentStatus: 'none',
    submittedAt: new Date(now - (DEMO_DRIVER_COUNT - i) * 3_600_000).toISOString(),
  }))
}

function buildDemoProtest(): Protest {
  const ds = drivers.slice(0, DEMO_DRIVER_COUNT)
  const now = Date.now()
  return {
    id: 'demo_protest_1',
    competitionId: DEMO_COMP_ID,
    roundId: DEMO_ROUND_ID,
    stageId: DEMO_RACE_STAGE_ID,
    sessionId: DEMO_RACE_SESSION_ID,
    reporterId: ds[1]?.id ?? 'd2',
    reportedId: ds[0]?.id ?? 'd1',
    type: 'dangerous',
    description: '正赛第 8 圈 1 号弯，被申诉车辆出弯接触导致本车失控。请裁判核查回放。',
    evidenceUrls: ['https://youtu.be/demo-incident'],
    lapNumber: 8,
    location: 'Turn 1',
    status: 'pending',
    createdAt: new Date(now - 1 * 3_600_000).toISOString(),
    deadline: new Date(now + 47 * 3_600_000).toISOString(),
  }
}

export function findDemoCompetition(): Competition | undefined {
  return competitions.find(c => c.id === DEMO_COMP_ID || c.isDemo)
}

export function createDemoScenario(): Competition {
  const existing = findDemoCompetition()
  if (existing) return existing
  const comp = buildDemoCompetition()
  competitions.push(comp)
  registrations.push(...buildDemoRegistrations())
  protests.push(buildDemoProtest())
  bump()
  return comp
}

export function resetDemoScenario(): void {
  for (let i = competitions.length - 1; i >= 0; i--) {
    if (competitions[i].id === DEMO_COMP_ID || competitions[i].isDemo) competitions.splice(i, 1)
  }
  for (let i = registrations.length - 1; i >= 0; i--) {
    if (registrations[i].id.startsWith('demo_reg_') || registrations[i].competitionId === DEMO_COMP_ID) registrations.splice(i, 1)
  }
  for (let i = protests.length - 1; i >= 0; i--) {
    if (protests[i].id.startsWith('demo_protest_') || protests[i].competitionId === DEMO_COMP_ID) protests.splice(i, 1)
  }
  for (let i = serverInstances.length - 1; i >= 0; i--) {
    if (serverInstances[i].stageId.startsWith('demo_comp_')) serverInstances.splice(i, 1)
  }
  bump()
}
